nopcommerce-4.50/Models/ConfigurationModel.cs
using Nop.Core.Configuration;
using Nop.Web.Framework.Models;
using System.Collections.Generic;

namespace Nop.Plugin.Misc.IARelatedProducts.Models
{
    /// <summary>
    /// Represents plugin configuration model
    /// </summary>
    public record ConfigurationModel : ISettings
    {
        public ConfigurationModel()
        {
            
        }

        public int PageSize { get; set; } = 10;

		public double Support { get; set; }
		public double Confidence { get; set; }
	}
}

nopcommerce-4.50/Models/RelatedProductsDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Web.Framework.Infrastructure;
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Misc.IARelatedProducts.Models
{
	public class ProductDTO 
	{
		public int Id { get; set; }

		public string Name { get; set; }

		public string Url { get; set; }

		public double Support { get; set; }

		public double Confidence { get; set; }
	}

    public record RelatedProductsDTO: BaseNopEntityModel
    {
        public string Name { get; set; }

		public ProductDTO MainProduct { get; set; }

		public ProductDTO Related1 { get; set; }
		public ProductDTO Related2 { get; set; }
		public ProductDTO Related3 { get; set; }
		public ProductDTO Related4 { get; set; }
		public ProductDTO Related5 { get; set; }
	}


}

nopcommerce-4.50/Models/RelatedProductsListModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Misc.IARelatedProducts.Models
{
    /// <summary>
    /// Represents a tax transaction log list model
    /// </summary>
    public record RelatedProductsListModel : BasePagedListModel<RelatedProductsDTO>    
    {
    }
}

nopcommerce-4.50/Models/RelatedProductsSearchModel.cs
using Nop.Web.Framework.Models;

namespace Nop.Plugin.Misc.IARelatedProducts.Models
{
    public record RelatedProductsSearchModel : BaseSearchModel
    {
        //public string Name { get; set; }
    
        public ColumnOptions[] Columns { get; set; }
        public Order[] Order { get; set; }
    }

    public class ColumnOptions
    {
        public string Data { get; set; }
        public string Name { get; set; }

        public bool Searchable { get; set; }

        public bool Orderable { get; set; }

    }

    public class Order
    {
        public int Column { get; set; }
        public string Dir { get; set; }
    }

}

nopcommerce-4.50/Controllers/IARelatedProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Services.Messages;
using Nop.Plugin.Misc.IARelatedProducts.Services;
using Nop.Core;
using System.Threading.Tasks;
using Nop.Plugin.Misc.IARelatedProducts.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Catalog;
using iTextSharp.text.html.simpleparser;
using Nop.Services.Media;
using DocumentFormat.OpenXml.Wordprocessing;
using Nop.Web.Framework.Models.Extensions;

namespace Nop.Plugin.Misc.IARelatedProducts.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class IARelatedProductsController : BasePluginController
    {

        #region Fields
		private readonly INotificationService _notificationService;
		private readonly IRelatedProductsService _relatedProductsService;
		private readonly IStoreContext _storeContext;
		private readonly ISettingService _settingService;
		private readonly ILocalizationService _localizationService;
		private readonly IPictureService _pictureService;
		#endregion

		#region Ctor

		public IARelatedProductsController(INotificationService notificationService, IPictureService pictureService, IRelatedProductsService relatedProductsService, IStoreContext storeContext, ISettingService settingService, ILocalizationService localizationService)
        {
			_pictureService = pictureService;
            _notificationService = notificationService;
            _relatedProductsService = relatedProductsService;
			_storeContext = storeContext;
			_settingService = settingService;
			_localizationService = localizationService;
		}

		#endregion


		#region Methods

		[AuthorizeAdmin]
		[Area(AreaNames.Admin)]
		public async Task<IActionResult> SaveModel()
		{
			await _relatedProductsService.SaveModel();
			_notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));
			return RedirectToAction("Configure");
		}

		[AuthorizeAdmin]
		[Area(AreaNames.Admin)]
		[HttpPost]
		public async Task<IActionResult> CreateModel()
		{
			var settings = await _settingService.LoadSettingAsync<ConfigurationModel>();
			await _relatedProductsService.GenerateModel(settings.Support, settings.Confidence);
			return await Configure();
		}

		[AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure()
        {
			ConfigurationModel model = await _settingService.LoadSettingAsync<ConfigurationModel>();
			return View("~/Plugins/Misc.IARelatedProducts/Views/Configure.cshtml", model); 
        }

	

		[AuthorizeAdmin]
		[Area(AreaNames.Admin)]
		[HttpPost, ActionName("Search")]
		public async Task<IActionResult> Search(RelatedProductsSearchModel searchModel) 
		{
			var data = await _relatedProductsService.SearchAsync(searchModel);

			var model = new RelatedProductsListModel().PrepareToGrid(searchModel, data, () =>
			{
				return data;
			});

			return Json(model);
		}


		[AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        [HttpPost]
		//, ActionName("Configure")]
  //      [FormValueRequired("save")]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
				return RedirectToAction("Configure");

			var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            await _settingService.SaveSettingAsync(model, storeId);
			await _settingService.ClearCacheAsync();

			_notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

			return await Configure();
		}

        #endregion
    }
}

nopcommerce-4.50/Views/Configure.cshtml
@using Nop.Plugin.Misc.IARelatedProducts.Models;
@using Nop.Web.Framework.Models.DataTables;


@model ConfigurationModel

@{
	Layout = "_ConfigurePlugin";
}


<div class="cards-group">
	<form asp-controller="IARelatedProducts" asp-action="configure">
		<div class="card card-default card-search form-horizontal">
			<div class="card-body">
				<div class="search-body" > 
					<div class="row">
						<div class="col-md-6">
							<div class="form-group row">
								<div class="col-md-4">
									<nop-label asp-for="@Model.Support" />
								</div>
								<div class="col-md-8">
									<nop-editor asp-for="@Model.Support" />
								</div>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group row">
								<div class="col-md-4">
									<nop-label asp-for="@Model.Confidence" />
								</div>
								<div class="col-md-8">
									<nop-editor asp-for="@Model.Confidence" />
								</div>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<div class="text-center col-12">
							<button  type="submit" class="btn btn-primary btn-search">
								<i class="fas fa-search"></i>
								@T("Admin.Common.Save")
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
	
	<form asp-controller="IARelatedProducts" asp-action="CreateModel">
		<div class="card card-default card-search form-horizontal">
			<div class="card-body">
				<div class="form-group row">
					<div class="text-center col-12">
						<button  type="submit" class="btn btn-primary btn-load">
							<i class="fas fa-load"></i>
							Load Model
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>
	<script>
		function renderProduct(data, type, row, meta) 
		{
			if (data == null)
				return '';
			var html = '<img src="' + data.Url + '" alt="' + data.Name + '" style="width: 100px;float: left" />';
			if (meta.col > 0)
				html += '<div>Suport: ' + data.Support.toFixed(4) + "</div><div>Confidence: " + data.Confidence.toFixed(4) + "</div>";
			return html;
		}
	</script>

	@await Html.PartialAsync("Table", new DataTablesModel
	{
		Name = "RelatedProduct-grid",
		UrlRead = new DataUrl("Search", "IARelatedProducts"),
		Processing = true,
		Paging = true,
		SearchButtonId = "search-relatedproducts",
		Info = false,
		Length = Model.PageSize,
		LengthMenu = "10,20,30",
		ColumnCollection = new List<ColumnProperty>
		{
			new ColumnProperty(nameof(RelatedProductsDTO.MainProduct))
			{
				Title = "Main",Render = new RenderCustom("renderProduct"), Width = "100px"
			},
			new ColumnProperty(nameof(RelatedProductsDTO.Related1))
			{
				Title = "Product1",Render = new RenderCustom("renderProduct"), Width = "100px"
			},
			new ColumnProperty(nameof(RelatedProductsDTO.Related2))
			{
				Title = "Product2",Render = new RenderCustom("renderProduct"), Width = "100px"
			},
			new ColumnProperty(nameof(RelatedProductsDTO.Related3))
			{
				Title = "Product3",Render = new RenderCustom("renderProduct"), Width = "100px"
			},
			new ColumnProperty(nameof(RelatedProductsDTO.Related4))
			{
				Title = "Product4",Render = new RenderCustom("renderProduct"), Width = "100px"
			},
			new ColumnProperty(nameof(RelatedProductsDTO.Related5))
			{
				Title = "Product5",Render = new RenderCustom("renderProduct"), Width = "100px"
			}
		}
	})

	<form asp-controller="IARelatedProducts" asp-action="SaveModel">
		<div class="card card-default card-search form-horizontal">
			<div class="card-body">
				<div class="form-group row">
					<div class="text-center col-12">
						<button type="submit" class="btn btn-primary btn-save">
							<i class="fas fa-save"></i>
							Save related products
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>	
</div>